#Clases, herencias y polimorfismos

###Definiciones.


In [ ]:
#Vamos a crear una definición en (que es una función integrada en python)
def Milanesi(a,b,c):
  x = a+b*c
  return x

In [ ]:
Milanesi (1,2,3)

7

In [ ]:
#Vamos a crear una definición que calcule la inversa de una matriz
import numpy as np
def Inv_Matrix(M):
  x = np.linalg.inv(M)
  return x

In [ ]:
b = np.array([[1,2,3], [0,1,0],[2,1,1]])
b

array([[1, 2, 3],
       [0, 1, 0],
       [2, 1, 1]])

In [ ]:
Inv_Matrix (b)

array([[-0.2, -0.2,  0.6],
       [ 0. ,  1. ,  0. ],
       [ 0.4, -0.6, -0.2]])

In [ ]:
#Matriz con data random, para que te lo deje fijos pones el seed (12)
np.random.seed (12)
y=np.random.randint(1,20,size=(2,2))
Inv_Matrix(y)

array([[-0.03333333,  0.07777778],
       [ 0.2       , -0.13333333]])

In [ ]:
y

array([[12,  7],
       [18,  3]])

In [ ]:
#Te dice la dimensión de la matriz
b.shape

(3, 3)